//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Kira = new HashSet<Kira>();
        }
    
        public string aracId { get; set; }
        public string aracPlaka { get; set; }
        public string aracRenk { get; set; }
        public int aracKiraUcret { get; set; }
        public string aracMarka { get; set; }
        public string aracKiralayanId { get; set; }
    
        public virtual Kiralayan Kiralayan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kira> Kira { get; set; }
    }
}
